parameters:
  # Required
  - name: "ENVIRONMENT"
    type: string
    values:
      - DEV
      - UAT
    default: DEV
  - name: "SEARCH_TRANSACTIONS_TOKEN_DEV"
    type: string
    default: ''
  - name: "SEARCH_TRANSACTIONS_TOKEN_UAT"
    type: string
    default: ''

steps:
  - script: |
      sed -i "s/^SEARCH_TRANSACTIONS_TOKEN.*$/SEARCH_TRANSACTIONS_TOKEN=${{parameters.SEARCH_TRANSACTIONS_TOKEN_DEV}}/" tests/e2e-tests/dev.env
    displayName: 'Set env for E2E test (DEV)'
    condition: and(succeeded(), eq('${{parameters.ENVIRONMENT}}', 'DEV'))
  - script: |
      sed -i "s/^SEARCH_TRANSACTIONS_TOKEN.*$/SEARCH_TRANSACTIONS_TOKEN=${{parameters.SEARCH_TRANSACTIONS_TOKEN_UAT}}/" tests/e2e-tests/uat.env
    displayName: 'Set env for E2E test (UAT)'
    condition: and(succeeded(), eq('${{parameters.ENVIRONMENT}}', 'UAT'))

  - script: yarn e2e-tests-dev
    displayName: 'Playwright E2E tests DEV'
    condition: and(succeeded(), eq('${{parameters.ENVIRONMENT}}', 'DEV'))
    continueOnError: true

  - script: yarn e2e-tests-uat
    displayName: 'Playwright E2E tests UAT'
    condition: and(succeeded(), eq('${{parameters.ENVIRONMENT}}', 'UAT'))
    continueOnError: true

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/*-TEST.xml'
      searchFolder: '$(System.DefaultWorkingDirectory)'
    condition: succeededOrFailed()