apiVersion: v2
type: application
version: 2.9.0
appVersion: "0.2.0"
name: pagopa-search-transactions-fe
description: React Typescript frontend application designed to support CIE transactions payment
dependencies:
  - name: microservice-chart
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
    version: 8.1.1
